services:
  wordpress:
    depends_on:
      - db
    image: wordpress:6.7
    ports:
      - "8000:80"
    # networks:
    #   - dokploy-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: portfolio
    volumes:
      - wordpress_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads

  db:
    image: mysql
    # networks:
    #   - dokploy-network
    restart: always
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  wordpress_data:
  db_data:
# networks:
#   dokploy-network:
#     external: true
